//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Wallet
    {
        public System.Guid WalletId { get; set; }
        public string CoinType { get; set; }
        public string PublicAddress { get; set; }
        public string PublicKey { get; set; }
        public string PrivateKey { get; set; }
        public string MemoCode { get; set; }
        public System.Guid FK_UserId { get; set; }
        public decimal Value { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public bool Enable { get; set; }
        public System.DateTime LastUpdateDatetime { get; set; }
    
        public virtual Tbl_user Tbl_user { get; set; }
    }
}
